### ISSUE TITLE
Auto-generate the release notes upon release

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/java-http-client#105]
#### Issue Summary

For every release, we hand craft the release notes on GitHub, now we would like to automate this process. Please see the existing [release notes](https://github.com/sendgrid/java-http-client/releases) for an example. The contents of the release notes are generated from the CHANGELOG.md file. [Here](https://developer.github.com/v3/repos/releases/#create-a-release) is the documentation for updating the release notes via the GitHub API. 

#### Acceptance Criteria
 

* A script, which when run, creates a release note update based on the last deployed release

**Comment by berry120** [comment]
@thinkingserious I'd like to grab this if available. Any preference for the language the script is written in? Happy to do it in Java, or something else if you prefer.

**Comment by childish-sambino** [comment]
Closing as we're now using internal tooling for this.
