### ISSUE TITLE
Bring Apache HttpComponents dependencies current

### ISSUE THREAD

**Issue by kebeda** [sendgrid/java-http-client#116]
#### Issue Summary

java-http-client 4.1.0 currently depends on org.apache.httpcomponents:httpcore:4.4.4, upgrade this to 4.4.12. It also depends on org.apache.httpcomponents:httpclient:4.5.2, upgrade this to 4.5.10.

This reduces enforcer violations when combined with any of the popular libraries that also depend upon httpcomponents (e.g., aws-java-sdk), and makes it easier to compile/use with Java 11.

#### Technical details:

* java-http-client Version: 4.1.0
* Java Version: 1.8

**Comment by thinkingserious** [comment]
Thank you @kebeda!
