### ISSUE TITLE
Unable to test under Java 11

### ISSUE THREAD

**Issue by kebeda** [sendgrid/java-http-client#118]
#### Issue Summary

Although java-http-client compiles just fine with the Java 11 JDK, maven is unable to run the test command because of a dependency on an inappropriate version of the jacoco-maven-plugin. Bringing this dependency current will allow testing on Java 11 as well as all previous JDKs.

#### Steps to Reproduce

1. Make sure maven is using a Java 11 JDK
2. `mvn test`

I expect to be able to compile and test java-http-client no matter what version of the JDK is used.

#### Technical details:

* java-http-client Version: 4.1.0
* Java Version: 11

**Comment by thinkingserious** [comment]
Hello @kebeda,

It looks like we are now up to date now. That said, thanks so much for taking the time to report this and to submit a PR. Much appreciated!

With best regards,

Elmer
