### ISSUE TITLE
mockito-core runtime dependency

### ISSUE THREAD

**Issue by jmadureira** [sendgrid/java-http-client#18]
#### Issue Summary

The current build.gradle configuration specifies mockito-core has a runtime dependency as opposed to the pom.xml which includes it as a test dependency.

You seem to be using Gradle for publishing since the current 4.0.0 version dependency tree has mockito-core scoped to runtime.
Is this expected or should it be scoped to test?

#### Technical details:

* java-http-client Version: master and 4.0.0 at least

**Comment by thinkingserious** [comment]
Hello @jmadureira,

You are correct, it should be scoped to test.

I've added this to our backlog for a fix.

**Comment by ubaldop** [comment]
May I take this?

**Comment by thinkingserious** [comment]
@P3trur0,

Yes please, thanks!
