### ISSUE TITLE
Class not found SendGridResponseHandler

### ISSUE THREAD

**Issue by PrinceVarshney** [sendgrid/java-http-client#20]
#### Issue Summary

I am getting classnotFound: SendgridResponseHandler, sometimes I am getting java.lang.ClassNotFoundException: org.apache.http.impl.client.AbstractResponseHandler but the mail is being sent. While fetching the response data , it is giving this error. I suppose some mismatch of jar versions.

#### Technical details:

* java-http-client Version: 4.1.0
* Java Version: 1.7
* SendGrid-java : 3.1.0

**Comment by thinkingserious** [comment]
Hello @PrinceVarshney,

Please follow this issue: https://github.com/sendgrid/sendgrid-java/pull/162

Thanks!
