### ISSUE TITLE
When creating a `new Client` allow suppling both underlying client and isTest parameter

### ISSUE THREAD

**Issue by maximn** [sendgrid/java-http-client#21]
#### Issue Summary

I want to supply an underlying HTTP Client to be able to set a timeout and as well set the `test` property.

Currently, these are the constructors exists-
	public Client()
	public Client(CloseableHttpClient httpClient)
	public Client(Boolean test)

I will add another constructor that gets these two parameters.

Seems that the intention of passing the http was for mocking but another use case is to be able to set up the http client (for example set up timeout).

**Comment by thinkingserious** [comment]
Thank you @maximn!
