### ISSUE TITLE
Demonstrate how to review the request body for troubleshooting

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/java-http-client#37]
When debugging, it can be useful to examine the request body before sending to the SendGrid API.

Prove an example of how to examine the request body in TROUBLESHOOTING.md. For an example, see [here](https://github.com/sendgrid/sendgrid-python/blob/master/TROUBLESHOOTING.md#request-body).

**Comment by vkdrn** [comment]
@thinkingserious Hi. I'll take this one

**Comment by mptap** [comment]
@thinkingserious: Here's https://github.com/sendgrid/java-http-client/pull/42 in case it's still up for grabs
