### ISSUE TITLE
gradle failure with openjdk7 in TravisCI

### ISSUE THREAD

**Issue by mbernier** [sendgrid/java-http-client#44]
#### Issue Summary

There is a gradle error when running against OpenJDK7 in TravisCI. 

See here: https://travis-ci.org/sendgrid/java-http-client/builds/291643842?utm_source=github_status&utm_medium=notification

Specifically the error is:
```
The command "eval ./gradlew assemble " failed 3 times.
```

**Comment by kazoni** [comment]
Fixed by #45, Java 7 support in gradle being depreciated per https://github.com/gradle/gradle/issues/2421#issuecomment-330890645

**Comment by diegorramos** [comment]
Fixed, by PR #46
