### ISSUE TITLE
Add a TROUBLESHOOTING.md file here please

### ISSUE THREAD

**Issue by mbernier** [sendgrid/java-http-client#51]
#### Issue Summary

Borrow the file from [sendgrid-java](https://github.com/sendgrid/sendgrid-java/blob/master/TROUBLESHOOTING.md) and modify it to fit this repo! 

Please make sure you show how to output the SMTPAPI header

**Comment by mptap** [comment]
@mbernier: PR: https://github.com/sendgrid/java-http-client/pull/56
