### ISSUE TITLE
Multi-byte character got garbled on received mail.

### ISSUE THREAD

**Issue by kikutaro** [sendgrid/java-http-client#6]
#### Issue Summary

When I was sending mail with Japanese multi-byte character via sendgrid-java v3.0.2, the received mail contents got garbled.Ex. こんにちは -> ?????

![capture2](https://cloud.githubusercontent.com/assets/5179168/16727010/f795b4e0-4799-11e6-83fa-ea3fb31bd211.JPG)

Pretty similar #4 but this is not sending but receiving.
#### Steps to Reproduce

Following simple code.

```
SendGrid sg = new SendGrid("api keys");
Request request = new Request();
Email from = new Email("from@from.co.jp");
String subject = "こんにちは";
Email to = new Email("to@to.co.jp");
Content content = new Content("text/plain", "こんにちは");
Mail mail = new Mail(from, subject, to, content);

request.method = Method.POST;
request.endpoint = "mail/send";
request.body = mail.build();
Response response = sg.api(request);
```

I tried curl command with multi-byte, it worked fine. The result means issue on library side.
#### Technical details:
- java-http-client Version: 2.3.1
- sendgrid-java Version:3.0.2
- Java Version: JDK 8u66

**Comment by kikutaro** [comment]
@thinkingserious I checkd the code both sendgrid-java and java-http-client.
I think the response also needs Charset UTF-8 like following.

```
-- responseBody = handler.handleResponse(response);
++ responseBody = EntityUtils.toString(response.getEntity(), StandardCharsets.UTF_8);
```

I tried this on my fork code, and it worked.
![solve](https://cloud.githubusercontent.com/assets/5179168/16727783/beff0de4-479d-11e6-969b-e783444ea2a5.JPG)
This caused by the default encoding is ISO-8859-1 of HttpClient's Response Body.
http://hc.apache.org/httpclient-3.x/charencodings.html

**Comment by thinkingserious** [comment]
https://github.com/sendgrid/java-http-client/releases/tag/v2.3.4
