### ISSUE TITLE
Allow a timeout value to be set

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/java-http-client#8]
These values should be configurable

.setSocketTimeout(timeout)
.setConnectTimeout(timeout)
.setConnectionRequestTimeout(timeout)

**Comment by ikatkov** [comment]
Created a PR for reference. Since I have not signed CLA I don't expect it to be merged.

**Comment by ikatkov** [comment]
ping?

**Comment by thinkingserious** [comment]
Thanks for the ping @ikatkov,

I see that three others have upvoted this issue, so I've updated our internal queue to help push this issue higher in the backlog.

The issue can continue to rise in the queue by:
1. More upvotes or comments
2. A pull request with a signed CLA

**Comment by dmaicher** [comment]
This would also be solved with https://github.com/sendgrid/sendgrid-java/pull/158

**Comment by thinkingserious** [comment]
Solved with https://github.com/sendgrid/sendgrid-java/pull/158
