### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "org.apache.http.impl.client.HttpClients"

### ISSUE THREAD

**Issue by sagar15bhavsar** [sendgrid/java-http-client#9]
I am getting 

java.lang.ClassNotFoundException: Didn't find class "org.apache.http.impl.client.HttpClients"

Please help !

**Comment by thinkingserious** [comment]
Hello @sagar15bhavsar,

It sounds like your dependencies did not load correctly. Could you please provide us with some additional details about your development environment? Particularly, how did you install the library?

**Comment by sagar15bhavsar** [comment]
I have installed library using Gradle. 
![screen shot 2016-07-18 at 10 12 30 pm](https://cloud.githubusercontent.com/assets/1187797/16923037/e623fc98-4d35-11e6-84e0-ca60c4cce152.png)

**Comment by thinkingserious** [comment]
Thanks!

You can remove `compile 'com.sendgrid:java-http-client:2.3.1` since sendgrid-java already has that dependency.

**Comment by sagar15bhavsar** [comment]
I removed it. Still getting error.

**Comment by thinkingserious** [comment]
It looks like that library has been deprecated in Android, here are a few workarounds that may help:

http://stackoverflow.com/questions/32960599/android-cannot-access-org-apache-http-client-httpclient
http://www.mkyong.com/java/the-type-defaulthttpclient-is-deprecated
http://stackoverflow.com/questions/30423677/dependency-issues-in-reference-project
